
import { Word } from './types.ts';

export const GRADES = [1, 2, 3, 4, 5, 6];

export const MOCK_WORDS: Word[] = [
  // --- 三年级上册 (最新版外研版一起点) 完整替换 ---
  
  // Welcome Unit (标注为 unit: 0)
  { id: '3-0-1', english: 'hi', chinese: '嘿，喂，你好', phonetic: '/haɪ/', grade: 3, unit: 0 },
  { id: '3-0-2', english: 'I', chinese: '我', phonetic: '/aɪ/', grade: 3, unit: 0 },
  { id: '3-0-3', english: 'am', chinese: '是', phonetic: '/æm/', grade: 3, unit: 0 },
  { id: '3-0-4', english: 'is', chinese: '是', phonetic: '/ɪz/', grade: 3, unit: 0 },
  { id: '3-0-5', english: 'are', chinese: '是', phonetic: '/ɑː(r)/', grade: 3, unit: 0 },
  { id: '3-0-6', english: 'what', chinese: '什么', phonetic: '/wɒt/', grade: 3, unit: 0 },
  { id: '3-0-7', english: 'your', chinese: '你的；你们的', phonetic: '/jɔː(r)/', grade: 3, unit: 0 },
  { id: '3-0-8', english: 'name', chinese: '名字', phonetic: '/neɪm/', grade: 3, unit: 0 },
  { id: '3-0-9', english: 'hello', chinese: '喂，哈啰，你好', phonetic: '/həˈləʊ/', grade: 3, unit: 0 },
  { id: '3-0-10', english: 'my', chinese: '我的', phonetic: '/maɪ/', grade: 3, unit: 0 },
  { id: '3-0-11', english: 'goodbye', chinese: '再见', phonetic: '/ˌɡʊdˈbaɪ/', grade: 3, unit: 0 },
  { id: '3-0-12', english: 'have', chinese: '有，拥有', phonetic: '/hæv/', grade: 3, unit: 0 },
  { id: '3-0-13', english: 'a', chinese: '一（个）', phonetic: '/ə/', grade: 3, unit: 0 },
  { id: '3-0-14', english: 'an', chinese: '一（个）', phonetic: '/æn/', grade: 3, unit: 0 },
  { id: '3-0-15', english: 'nice', chinese: '令人愉快的', phonetic: '/naɪs/', grade: 3, unit: 0 },
  { id: '3-0-16', english: 'day', chinese: '一天', phonetic: '/deɪ/', grade: 3, unit: 0 },
  { id: '3-0-17', english: 'good', chinese: '好的', phonetic: '/ɡʊd/', grade: 3, unit: 0 },
  { id: '3-0-18', english: 'morning', chinese: '早晨，上午', phonetic: '/ˈmɔːnɪŋ/', grade: 3, unit: 0 },
  { id: '3-0-19', english: 'Ms', chinese: '女士', phonetic: '/mɪz/', grade: 3, unit: 0 },
  { id: '3-0-20', english: 'stand', chinese: '站立', phonetic: '/stænd/', grade: 3, unit: 0 },
  { id: '3-0-21', english: 'stand up', chinese: '站起来', phonetic: '/stænd ʌp/', grade: 3, unit: 0 },
  { id: '3-0-22', english: 'sit', chinese: '坐', phonetic: '/sɪt/', grade: 3, unit: 0 },
  { id: '3-0-23', english: 'sit down', chinese: '坐下', phonetic: '/sɪt daʊn/', grade: 3, unit: 0 },
  { id: '3-0-24', english: 'open', chinese: '打开', phonetic: '/ˈəʊpən/', grade: 3, unit: 0 },
  { id: '3-0-25', english: 'book', chinese: '书', phonetic: '/bʊk/', grade: 3, unit: 0, emoji: '📖' },
  { id: '3-0-26', english: 'close', chinese: '合上', phonetic: '/kləʊz/', grade: 3, unit: 0 },
  { id: '3-0-27', english: 'point', chinese: '指', phonetic: '/pɔɪnt/', grade: 3, unit: 0 },
  { id: '3-0-28', english: 'say', chinese: '说', phonetic: '/seɪ/', grade: 3, unit: 0 },
  { id: '3-0-29', english: 'read', chinese: '阅读', phonetic: '/riːd/', grade: 3, unit: 0 },
  { id: '3-0-30', english: 'listen', chinese: '听', phonetic: '/ˈlɪsn/', grade: 3, unit: 0 },
  { id: '3-0-31', english: 'write', chinese: '写', phonetic: '/raɪt/', grade: 3, unit: 0 },

  // Unit 1
  { id: '3-1-1', english: "let's", chinese: '让我们', phonetic: '/lets/', grade: 3, unit: 1 },
  { id: '3-1-2', english: 'friend', chinese: '朋友', phonetic: '/frend/', grade: 3, unit: 1, emoji: '👫' },
  { id: '3-1-3', english: 'to', chinese: '向，到，往', phonetic: '/tu/', grade: 3, unit: 1 },
  { id: '3-1-4', english: 'meet', chinese: '认识，结识', phonetic: '/miːt/', grade: 3, unit: 1 },
  { id: '3-1-5', english: 'you', chinese: '你；你们', phonetic: '/ju/', grade: 3, unit: 1 },
  { id: '3-1-6', english: 'play', chinese: '玩，玩耍', phonetic: '/pleɪ/', grade: 3, unit: 1 },
  { id: '3-1-7', english: 'happy', chinese: '高兴的，快乐的', phonetic: '/ˈhæpi/', grade: 3, unit: 1, emoji: '😊' },
  { id: '3-1-8', english: 'new', chinese: '新的', phonetic: '/njuː/', grade: 3, unit: 1 },
  { id: '3-1-9', english: 'do', chinese: '做', phonetic: '/duː/', grade: 3, unit: 1 },
  { id: '3-1-10', english: 'they', chinese: '他们', phonetic: '/ðeɪ/', grade: 3, unit: 1 },
  { id: '3-1-11', english: 'welcome', chinese: '欢迎', phonetic: '/ˈwelkəm/', grade: 3, unit: 1 },
  { id: '3-1-12', english: 'everyone', chinese: '每个人，人人', phonetic: '/ˈevriwʌn/', grade: 3, unit: 1 },
  { id: '3-1-13', english: 'nine', chinese: '九', phonetic: '/naɪn/', grade: 3, unit: 1 },
  { id: '3-1-14', english: 'she', chinese: '她', phonetic: '/ʃiː/', grade: 3, unit: 1 },
  { id: '3-1-15', english: 'too', chinese: '也', phonetic: '/tuː/', grade: 3, unit: 1 },
  { id: '3-1-16', english: 'we', chinese: '我们', phonetic: '/wiː/', grade: 3, unit: 1 },
  { id: '3-1-17', english: 'from', chinese: '从', phonetic: '/frəm/', grade: 3, unit: 1 },
  { id: '3-1-18', english: 'the', chinese: '特指人/物', phonetic: '/ðə/', grade: 3, unit: 1 },
  { id: '3-1-19', english: 'twin', chinese: '双胞胎中的一个', phonetic: '/twɪn/', grade: 3, unit: 1 },
  { id: '3-1-20', english: 'he', chinese: '他', phonetic: '/hiː/', grade: 3, unit: 1 },
  { id: '3-1-21', english: 'come', chinese: '来；来到', phonetic: '/kʌm/', grade: 3, unit: 1 },
  { id: '3-1-22', english: 'and', chinese: '然后；接着；和', phonetic: '/ænd/', grade: 3, unit: 1 },
  { id: '3-1-23', english: 'oh', chinese: '噢', phonetic: '/əʊ/', grade: 3, unit: 1 },
  { id: '3-1-24', english: 'no', chinese: '不，不行', phonetic: '/nəʊ/', grade: 3, unit: 1 },
  { id: '3-1-25', english: 'help', chinese: '帮助，帮忙', phonetic: '/help/', grade: 3, unit: 1 },
  { id: '3-1-26', english: 'here', chinese: '在这里', phonetic: '/hɪə(r)/', grade: 3, unit: 1 },
  { id: '3-1-27', english: 'here you are', chinese: '给你', phonetic: '/hɪə(r) ju ɑː(r)/', grade: 3, unit: 1 },
  { id: '3-1-28', english: 'thank', chinese: '感谢', phonetic: '/θæŋk/', grade: 3, unit: 1 },
  { id: '3-1-29', english: 'together', chinese: '一起，一块儿', phonetic: '/təˈɡeðə(r)/', grade: 3, unit: 1 },
  { id: '3-1-30', english: 'OK', chinese: '行，可以', phonetic: '/ˌəʊ ˈkeɪ/', grade: 3, unit: 1 },
  { id: '3-1-31', english: 'great', chinese: '极棒的，极好的', phonetic: '/ɡreɪt/', grade: 3, unit: 1 },
  { id: '3-1-32', english: 'song', chinese: '歌曲', phonetic: '/sɒŋ/', grade: 3, unit: 1, emoji: '🎵' },
  { id: '3-1-33', english: 'dear', chinese: '亲爱的', phonetic: '/dɪə(r)/', grade: 3, unit: 1 },
  { id: '3-1-34', english: 'sing', chinese: '唱，歌唱', phonetic: '/sɪŋ/', grade: 3, unit: 1 },
  { id: '3-1-35', english: 'now', chinese: '现在', phonetic: '/naʊ/', grade: 3, unit: 1 },
  { id: '3-1-36', english: 'know', chinese: '认识', phonetic: '/nəʊ/', grade: 3, unit: 1 },
  { id: '3-1-37', english: 'our', chinese: '我们的', phonetic: '/ˈaʊə(r)/', grade: 3, unit: 1 },
  { id: '3-1-38', english: 'everybody', chinese: '每个人，人人', phonetic: '/ˈevribɒdi/', grade: 3, unit: 1 },

  // Unit 2
  { id: '3-2-1', english: 'school', chinese: '学校', phonetic: '/skuːl/', grade: 3, unit: 2, emoji: '🏫' },
  { id: '3-2-2', english: 'thing', chinese: '东西', phonetic: '/θɪŋ/', grade: 3, unit: 2 },
  { id: '3-2-3', english: 'pack', chinese: '收拾好', phonetic: '/pæk/', grade: 3, unit: 2 },
  { id: '3-2-4', english: 'pen', chinese: '钢笔', phonetic: '/pen/', grade: 3, unit: 2, emoji: '🖊️' },
  { id: '3-2-5', english: 'pencil', chinese: '铅笔', phonetic: '/ˈpensl/', grade: 3, unit: 2, emoji: '✏️' },
  { id: '3-2-6', english: 'pencil case', chinese: '笔袋；铅笔盒', phonetic: '/ˈpensl keɪs/', grade: 3, unit: 2 },
  { id: '3-2-7', english: 'bag', chinese: '袋；包', phonetic: '/bæɡ/', grade: 3, unit: 2, emoji: '🎒' },
  { id: '3-2-8', english: 'for', chinese: '为了', phonetic: '/fɔː(r)/', grade: 3, unit: 2 },
  { id: '3-2-9', english: 'ruler', chinese: '尺子，直尺', phonetic: '/ˈruːlə(r)/', grade: 3, unit: 2, emoji: '📏' },
  { id: '3-2-10', english: 'eraser', chinese: '橡皮', phonetic: '/ɪˈreɪsə(r)/', grade: 3, unit: 2 },
  { id: '3-2-11', english: 'this', chinese: '这，这个', phonetic: '/ðɪs/', grade: 3, unit: 2 },
  { id: '3-2-12', english: 'in', chinese: '在……里', phonetic: '/ɪn/', grade: 3, unit: 2 },
  { id: '3-2-13', english: 'schoolbag', chinese: '书包', phonetic: '/ˈskuːlbæɡ/', grade: 3, unit: 2 },
  { id: '3-2-14', english: 'it', chinese: '它', phonetic: '/ɪt/', grade: 3, unit: 2 },
  { id: '3-2-15', english: 'not', chinese: '不，不是', phonetic: '/nɒt/', grade: 3, unit: 2 },
  { id: '3-2-16', english: 'that', chinese: '那，那个', phonetic: '/ðæt/', grade: 3, unit: 2 },
  { id: '3-2-17', english: 'yes', chinese: '是，对', phonetic: '/jes/', grade: 3, unit: 2 },
  { id: '3-2-18', english: 'guess', chinese: '猜，猜测', phonetic: '/ɡes/', grade: 3, unit: 2 },
  { id: '3-2-19', english: 'find', chinese: '发现，找到', phonetic: '/faɪnd/', grade: 3, unit: 2 },
  { id: '3-2-20', english: 'lost and found', chinese: '失物招领', phonetic: '/lɒst ənd faʊnd/', grade: 3, unit: 2 },
  { id: '3-2-21', english: 'bye', chinese: '再见，拜拜', phonetic: '/baɪ/', grade: 3, unit: 2 },
  { id: '3-2-22', english: 'kid', chinese: '小孩', phonetic: '/kɪd/', grade: 3, unit: 2 },
  { id: '3-2-23', english: 'take care of', chinese: '照看（照料）', phonetic: '/teɪk keə(r) əv/', grade: 3, unit: 2 },
  { id: '3-2-24', english: 'there', chinese: '在那里', phonetic: '/ðeə(r)/', grade: 3, unit: 2 },
  { id: '3-2-25', english: 'please', chinese: '请', phonetic: '/pliːz/', grade: 3, unit: 2 },
  { id: '3-2-26', english: 'back', chinese: '回到原处', phonetic: '/bæk/', grade: 3, unit: 2 },
  { id: '3-2-27', english: 'come back', chinese: '回来', phonetic: '/kʌm bæk/', grade: 3, unit: 2 },
  { id: '3-2-28', english: 'look', chinese: '看，瞧，望', phonetic: '/lʊk/', grade: 3, unit: 2 },
  { id: '3-2-29', english: 'look at', chinese: '看某人/某物', phonetic: '/lʊk æt/', grade: 3, unit: 2 },

  // Unit 3
  { id: '3-3-1', english: 'colourful', chinese: '颜色鲜艳的', phonetic: '/ˈkʌləfl/', grade: 3, unit: 3 },
  { id: '3-3-2', english: 'world', chinese: '世界', phonetic: '/wɜːld/', grade: 3, unit: 3 },
  { id: '3-3-3', english: 'hooray', chinese: '好哇', phonetic: '/huˈreɪ/', grade: 3, unit: 3 },
  { id: '3-3-4', english: 'umbrella', chinese: '伞；雨伞', phonetic: '/ʌmˈbrelə/', grade: 3, unit: 3, emoji: '☂️' },
  { id: '3-3-5', english: 'clothes', chinese: '衣服', phonetic: '/kləʊðz/', grade: 3, unit: 3, emoji: '👕' },
  { id: '3-3-6', english: 'red', chinese: '红色（的）', phonetic: '/red/', grade: 3, unit: 3, emoji: '🔴' },
  { id: '3-3-7', english: 'pink', chinese: '粉红色（的）', phonetic: '/pɪŋk/', grade: 3, unit: 3, emoji: '🌸' },
  { id: '3-3-8', english: 'green', chinese: '绿色（的）', phonetic: '/ɡriːn/', grade: 3, unit: 3, emoji: '🟢' },
  { id: '3-3-9', english: 'yellow', chinese: '黄色（的）', phonetic: '/ˈjeləʊ/', grade: 3, unit: 3, emoji: '🟡' },
  { id: '3-3-10', english: 'orange', chinese: '橙色（的）', phonetic: '/ˈɒrɪndʒ/', grade: 3, unit: 3, emoji: '🟠' },
  { id: '3-3-11', english: 'blue', chinese: '蓝色（的）', phonetic: '/bluː/', grade: 3, unit: 3, emoji: '🔵' },
  { id: '3-3-12', english: 'purple', chinese: '紫色（的）', phonetic: '/ˈpɜːpl/', grade: 3, unit: 3, emoji: '🟣' },
  { id: '3-3-13', english: 'rainbow', chinese: '彩虹', phonetic: '/ˈreɪnbəʊ/', grade: 3, unit: 3, emoji: '🌈' },
  { id: '3-3-14', english: 'want', chinese: '想要', phonetic: '/wɒnt/', grade: 3, unit: 3 },
  { id: '3-3-15', english: 'balloon', chinese: '气球', phonetic: '/bəˈluːn/', grade: 3, unit: 3, emoji: '🎈' },
  { id: '3-3-16', english: 'colour', chinese: '颜色', phonetic: '/ˈkʌlə(r)/', grade: 3, unit: 3 },
  { id: '3-3-17', english: 'can', chinese: '能，会', phonetic: '/kæn/', grade: 3, unit: 3 },
  { id: '3-3-18', english: 'see', chinese: '看见，看到', phonetic: '/siː/', grade: 3, unit: 3 },
  { id: '3-3-19', english: 'right', chinese: '正确的，对的', phonetic: '/raɪt/', grade: 3, unit: 3 },
  { id: '3-3-20', english: 'first', chinese: '第一的；首先', phonetic: '/fɜːst/', grade: 3, unit: 3 },
  { id: '3-3-21', english: 'magical', chinese: '美妙的；有魔力的', phonetic: '/ˈmædʒɪkl/', grade: 3, unit: 3 },
  { id: '3-3-22', english: 'fun', chinese: '有趣的，逗乐的', phonetic: '/fʌn/', grade: 3, unit: 3 },
  { id: '3-3-23', english: 'black', chinese: '黑色（的）', phonetic: '/blæk/', grade: 3, unit: 3, emoji: '⚫' },
  { id: '3-3-24', english: 'so', chinese: '这么，如此', phonetic: '/səʊ/', grade: 3, unit: 3 },
  { id: '3-3-25', english: 'many', chinese: '许多；大量', phonetic: '/ˈmeni/', grade: 3, unit: 3 },
  { id: '3-3-26', english: 'picture', chinese: '画，图画', phonetic: '/ˈpɪktʃə(r)/', grade: 3, unit: 3 },
  { id: '3-3-27', english: 'today', chinese: '今天', phonetic: '/təˈdeɪ/', grade: 3, unit: 3 },
  { id: '3-3-28', english: 'paint', chinese: '画，作画', phonetic: '/peɪnt/', grade: 3, unit: 3 },

  // Unit 4
  { id: '3-4-1', english: 'number', chinese: '数，数字', phonetic: '/ˈnʌmbə(r)/', grade: 3, unit: 4 },
  { id: '3-4-2', english: 'count', chinese: '数数', phonetic: '/kaʊnt/', grade: 3, unit: 4 },
  { id: '3-4-3', english: 'how', chinese: '多少；怎样，如何', phonetic: '/haʊ/', grade: 3, unit: 4 },
  { id: '3-4-4', english: 'bird', chinese: '鸟', phonetic: '/bɜːd/', grade: 3, unit: 4, emoji: '🐦' },
  { id: '3-4-5', english: 'one', chinese: '一', phonetic: '/wʌn/', grade: 3, unit: 4 },
  { id: '3-4-6', english: 'two', chinese: '二', phonetic: '/tuː/', grade: 3, unit: 4 },
  { id: '3-4-7', english: 'three', chinese: '三', phonetic: '/θriː/', grade: 3, unit: 4 },
  { id: '3-4-8', english: 'four', chinese: '四', phonetic: '/fɔː(r)/', grade: 3, unit: 4 },
  { id: '3-4-9', english: 'five', chinese: '五', phonetic: '/faɪ/', grade: 3, unit: 4 },
  { id: '3-4-10', english: 'six', chinese: '六', phonetic: '/sɪks/', grade: 3, unit: 4 },
  { id: '3-4-11', english: 'seven', chinese: '七', phonetic: '/ˈsevn/', grade: 3, unit: 4 },
  { id: '3-4-12', english: 'eight', chinese: '八', phonetic: '/eɪt/', grade: 3, unit: 4 },
  { id: '3-4-13', english: 'ten', chinese: '十', phonetic: '/ten/', grade: 3, unit: 4 },
  { id: '3-4-14', english: 'eleven', chinese: '十一', phonetic: '/ɪˈlevn/', grade: 3, unit: 4 },
  { id: '3-4-15', english: 'twelve', chinese: '十二', phonetic: '/twelv/', grade: 3, unit: 4 },
  { id: '3-4-16', english: 'rope', chinese: '绳', phonetic: '/rəʊp/', grade: 3, unit: 4 },
  { id: '3-4-17', english: 'who', chinese: '谁，什么人', phonetic: '/huː/', grade: 3, unit: 4 },
  { id: '3-4-18', english: 'make', chinese: '制作', phonetic: '/meɪk/', grade: 3, unit: 4 },
  { id: '3-4-19', english: 'Chinese knot', chinese: '中国结', phonetic: '/ˌtʃaɪˈniːz nɒt/', grade: 3, unit: 4 },
  { id: '3-4-20', english: 'beautiful', chinese: '美丽的', phonetic: '/ˈbjuːtɪfl/', grade: 3, unit: 4 },
  { id: '3-4-21', english: 'only', chinese: '仅仅', phonetic: '/ˈəʊnli/', grade: 3, unit: 4 },
  { id: '3-4-22', english: 'amazing', chinese: '令人惊讶的', phonetic: '/əˈmeɪzɪŋ/', grade: 3, unit: 4 },
  { id: '3-4-23', english: 'show', chinese: '给……看', phonetic: '/ʃəʊ/', grade: 3, unit: 4 },
  { id: '3-4-24', english: 'baby', chinese: '幼崽；雏鸟', phonetic: '/ˈbeɪbi/', grade: 3, unit: 4 },
  { id: '3-4-25', english: 'cheep', chinese: '吱吱叫声', phonetic: '/tʃiːp/', grade: 3, unit: 4 },
  { id: '3-4-26', english: 'egg', chinese: '蛋', phonetic: '/eɡ/', grade: 3, unit: 4, emoji: '🥚' },
  { id: '3-4-27', english: 'hungry', chinese: '饥饿的', phonetic: '/ˈhʌŋɡri/', grade: 3, unit: 4 },
  { id: '3-4-28', english: 'around', chinese: '环绕', phonetic: '/əˈraʊnd/', grade: 3, unit: 4 },
  { id: '3-4-29', english: 'all', chinese: '全部，所有', phonetic: '/ɔːl/', grade: 3, unit: 4 },
  { id: '3-4-30', english: 'all around', chinese: '处处，到处', phonetic: '/ɔːl əˈraʊnd/', grade: 3, unit: 4 },
  { id: '3-4-31', english: 'big', chinese: '大的', phonetic: '/bɪɡ/', grade: 3, unit: 4 },
  { id: '3-4-32', english: 'little', chinese: '小的', phonetic: '/ˈlɪtl/', grade: 3, unit: 4 },
  { id: '3-4-33', english: 'everywhere', chinese: '各个地方；处处', phonetic: '/ˈevriweə(r)/', grade: 3, unit: 4 },

  // Unit 5
  { id: '3-5-1', english: 'family', chinese: '家庭；家人', phonetic: '/ˈfæməli/', grade: 3, unit: 5, emoji: '👨‍👩‍👧‍👦' },
  { id: '3-5-2', english: 'dad', chinese: '爸爸', phonetic: '/dæd/', grade: 3, unit: 5 },
  { id: '3-5-3', english: 'father', chinese: '父亲', phonetic: '/ˈfɑːðə(r)/', grade: 3, unit: 5 },
  { id: '3-5-4', english: 'mum', chinese: '妈妈', phonetic: '/mʌm/', grade: 3, unit: 5 },
  { id: '3-5-5', english: 'mother', chinese: '母亲', phonetic: '/ˈmʌðə(r)/', grade: 3, unit: 5 },
  { id: '3-5-6', english: 'brother', chinese: '哥哥；弟弟', phonetic: '/ˈbrʌðə(r)/', grade: 3, unit: 5 },
  { id: '3-5-7', english: 'sister', chinese: '姐姐；妹妹', phonetic: '/ˈsɪstə(r)/', grade: 3, unit: 5 },
  { id: '3-5-8', english: 'grandpa', chinese: '祖父；外祖父', phonetic: '/ˈɡrænpɑː/', grade: 3, unit: 5 },
  { id: '3-5-9', english: 'grandfather', chinese: '祖父', phonetic: '/ˈɡrænfɑːðə(r)/', grade: 3, unit: 5 },
  { id: '3-5-10', english: 'grandma', chinese: '祖母；外祖母', phonetic: '/ˈɡrænmɑː/', grade: 3, unit: 5 },
  { id: '3-5-11', english: 'grandmother', chinese: '祖母', phonetic: '/ˈɡrænmʌðə(r)/', grade: 3, unit: 5 },
  { id: '3-5-12', english: 'but', chinese: '但是，然而', phonetic: '/bʌt/', grade: 3, unit: 5 },
  { id: '3-5-13', english: 'people', chinese: '人；人们', phonetic: '/ˈpiːpl/', grade: 3, unit: 5 },
  { id: '3-5-14', english: 'story', chinese: '故事', phonetic: '/ˈstɔːri/', grade: 3, unit: 5 },
  { id: '3-5-15', english: 'cap', chinese: '帽子', phonetic: '/kæp/', grade: 3, unit: 5, emoji: '🧢' },
  { id: '3-5-16', english: 'worry', chinese: '担心', phonetic: '/ˈwʌri/', grade: 3, unit: 5 },
  { id: '3-5-17', english: 'on', chinese: '在……上面', phonetic: '/ɒn/', grade: 3, unit: 5 },
  { id: '3-5-18', english: 'come on', chinese: '快点；加油', phonetic: '/kʌm ɒn/', grade: 3, unit: 5 },
  { id: '3-5-19', english: 'photo', chinese: '照片，相片', phonetic: '/ˈfəʊtəʊ/', grade: 3, unit: 5, emoji: '📷' },
  { id: '3-5-20', english: 'love', chinese: '爱，关爱', phonetic: '/lʌv/', grade: 3, unit: 5, emoji: '❤️' },
  { id: '3-5-21', english: 'daddy', chinese: '爸爸', phonetic: '/ˈdædi/', grade: 3, unit: 5 },
  { id: '3-5-22', english: 'mummy', chinese: '妈妈', phonetic: '/ˈmʌmi/', grade: 3, unit: 5 },
  { id: '3-5-23', english: 'where', chinese: '在哪里', phonetic: '/weə(r)/', grade: 3, unit: 5 },
  { id: '3-5-24', english: 'dog', chinese: '狗', phonetic: '/dɒɡ/', grade: 3, unit: 5, emoji: '🐶' },
  { id: '3-5-25', english: 'box', chinese: '盒；箱', phonetic: '/bɒks/', grade: 3, unit: 5 },

  // Unit 6
  { id: '3-6-1', english: 'sweet', chinese: '甜蜜的', phonetic: '/swiːt/', grade: 3, unit: 6 },
  { id: '3-6-2', english: 'home', chinese: '家', phonetic: '/həʊm/', grade: 3, unit: 6, emoji: '🏠' },
  { id: '3-6-3', english: 'game', chinese: '游戏', phonetic: '/ɡeɪm/', grade: 3, unit: 6 },
  { id: '3-6-4', english: 'room', chinese: '房间', phonetic: '/ruːm/', grade: 3, unit: 6 },
  { id: '3-6-5', english: 'living room', chinese: '客厅', phonetic: '/ˈlɪvɪŋ ruːm/', grade: 3, unit: 6 },
  { id: '3-6-6', english: 'bedroom', chinese: '卧室', phonetic: '/ˈbedruːm/', grade: 3, unit: 6 },
  { id: '3-6-7', english: 'bathroom', chinese: '浴室，卫生间', phonetic: '/ˈbɑːθruːm/', grade: 3, unit: 6 },
  { id: '3-6-8', english: 'kitchen', chinese: '厨房', phonetic: '/ˈkɪtʃɪn/', grade: 3, unit: 6 },
  { id: '3-6-9', english: 'dining room', chinese: '餐厅', phonetic: '/ˈdaɪnɪŋ ruːm/', grade: 3, unit: 6 },
  { id: '3-6-10', english: 'door', chinese: '门', phonetic: '/dɔː(r)/', grade: 3, unit: 6, emoji: '🚪' },
  { id: '3-6-11', english: 'chair', chinese: '椅子', phonetic: '/tʃeə(r)/', grade: 3, unit: 6, emoji: '🪑' },
  { id: '3-6-12', english: 'think', chinese: '想，认为', phonetic: '/θɪŋk/', grade: 3, unit: 6 },
  { id: '3-6-13', english: 'under', chinese: '在……下面', phonetic: '/ˈʌndə(r)/', grade: 3, unit: 6 },
  { id: '3-6-14', english: 'bed', chinese: '床', phonetic: '/bed/', grade: 3, unit: 6, emoji: '🛏️' },
  { id: '3-6-15', english: 'toy', chinese: '玩具', phonetic: '/tɔɪ/', grade: 3, unit: 6, emoji: '🧸' },
  { id: '3-6-16', english: 'miaow', chinese: '咪，喵', phonetic: '/miˈaʊ/', grade: 3, unit: 6 },
  { id: '3-6-17', english: 'table', chinese: '桌子', phonetic: '/ˈteɪbl/', grade: 3, unit: 6 },
  { id: '3-6-18', english: 'cat', chinese: '猫', phonetic: '/kæt/', grade: 3, unit: 6, emoji: '🐱' },
  { id: '3-6-19', english: 'ball', chinese: '球', phonetic: '/bɔːl/', grade: 3, unit: 6, emoji: '⚽' },
  { id: '3-6-20', english: 'their', chinese: '他们的', phonetic: '/ðeə(r)/', grade: 3, unit: 6 },
  { id: '3-6-21', english: 'apple', chinese: '苹果', phonetic: '/ˈæpl/', grade: 3, unit: 6, emoji: '🍎' },
  { id: '3-6-22', english: 'share', chinese: '共用；分享', phonetic: '/ʃeə(r)/', grade: 3, unit: 6 },
  { id: '3-6-23', english: 'put', chinese: '放', phonetic: '/pʊt/', grade: 3, unit: 6 },
  { id: '3-6-24', english: 'cooking', chinese: '做饭', phonetic: '/ˈkʊkɪŋ/', grade: 3, unit: 6 },
  { id: '3-6-25', english: 'sun', chinese: '太阳', phonetic: '/sʌn/', grade: 3, unit: 6, emoji: '☀️' },
  { id: '3-6-26', english: 'like', chinese: '喜欢', phonetic: '/laɪk/', grade: 3, unit: 6 },
  { id: '3-6-27', english: 'run', chinese: '跑', phonetic: '/rʌn/', grade: 3, unit: 6 },
  { id: '3-6-28', english: 'lucky', chinese: '幸运的', phonetic: '/ˈlʌki/', grade: 3, unit: 6 },

  // 其他年级占位
  { id: '1-1-1', english: 'hello', chinese: '你好', phonetic: '/həˈləʊ/', grade: 1, unit: 1 },
];
